services:
  db:
    container_name: pg_db
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data/
    stdin_open: true
    tty: true
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 5s
      timeout: 2s
      retries: 10

  server:
    container_name: go_server
    build:
      context: .
      dockerfile: Dev.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/src
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG
      - TESTING
      - DB_HOST=db
      - DB_NAME
      - DB_USER
      - DB_PORT
      - DB_PASSWORD
      - TRUSTED_PROXIES
      - SECRET

volumes:
  dev_postgres_data:
  pgadmin_data:
